apiVersion: v1
kind: Service  # Exposes applications (sets of pods) to network traffic
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80  # Port to expose externally
      targetPort: 80  # Port on the pod
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer